class ProductDetail {
  String id,
      brand,
      name,
      image,
      price,
      barcode,
      weight,
      cate,
      priceNhap,
      priceBuon,
      amount,
      desc,
      allowSale,
      tax,
      ngayUp,
      priceVon,
      daban;

  ProductDetail(
      this.id,
      this.brand,
      this.name,
      this.image,
      this.price,
      this.barcode,
      this.weight,
      this.cate,
      this.priceNhap,
      this.priceBuon,
      this.amount,
      this.desc,
      this.allowSale,
      this.tax,
      this.priceVon,
      this.ngayUp,
      this.daban);
}
